import React, { useState, useEffect } from 'react';
import { ChecklistItem as ChecklistItemType, ChecklistCategory, AIActionType } from './types';
import { INITIAL_CHECKLIST, INITIAL_CHART_DATA } from './constants';
import ChecklistItem from './components/ChecklistItem';
import ContentMixChart from './components/ContentMixChart';
import AIAssistant from './components/AIAssistant';
import { LayoutDashboard, Rocket, ArrowRight, Zap, Download, RefreshCw, Sparkles, CheckCircle2, Moon, Sun } from 'lucide-react';

const App: React.FC = () => {
  const [categories, setCategories] = useState<ChecklistCategory[]>(() => {
    // Initialize from localStorage if available
    if (typeof window !== 'undefined') {
        const saved = localStorage.getItem('contentFlowState');
        if (saved) {
            try {
                return JSON.parse(saved);
            } catch (e) {
                console.error("Failed to parse saved state", e);
            }
        }
    }
    return INITIAL_CHECKLIST;
  });
  
  const [progress, setProgress] = useState(0);
  const [isDarkMode, setIsDarkMode] = useState(false);
  
  // AI Modal State
  const [isAIModalOpen, setIsAIModalOpen] = useState(false);
  const [activeAIAction, setActiveAIAction] = useState<AIActionType | null>(null);
  const [activeAIContext, setActiveAIContext] = useState('');
  const [activeItemId, setActiveItemId] = useState<string | null>(null);

  // Save to localStorage whenever categories change
  useEffect(() => {
    localStorage.setItem('contentFlowState', JSON.stringify(categories));
  }, [categories]);

  // Calculate progress whenever checklist changes
  useEffect(() => {
    let total = 0;
    let completed = 0;
    
    categories.forEach(cat => {
      cat.items.forEach(item => {
        total++;
        if (item.isCompleted) completed++;
      });
    });

    setProgress(Math.round(total === 0 ? 0 : (completed / total) * 100));
  }, [categories]);

  const handleToggleItem = (itemId: string) => {
    setCategories(prev => prev.map(cat => ({
      ...cat,
      items: cat.items.map(item => 
        item.id === itemId ? { ...item, isCompleted: !item.isCompleted } : item
      )
    })));
  };

  const handleAITrigger = (action: AIActionType, itemText: string) => {
    // Find the item ID associated with this text to enable saving later
    let itemId = null;
    for (const cat of categories) {
        const item = cat.items.find(i => i.text === itemText);
        if (item) {
            itemId = item.id;
            break;
        }
    }
    setActiveItemId(itemId);
    setActiveAIAction(action);
    setActiveAIContext(itemText);
    setIsAIModalOpen(true);
  };

  const handleSaveAIContent = (content: string) => {
      if (!activeItemId) return;

      setCategories(prev => prev.map(cat => ({
          ...cat,
          items: cat.items.map(item => 
            item.id === activeItemId ? { ...item, savedContent: content, isCompleted: true } : item
          )
      })));
  };

  const handleReset = () => {
      if (window.confirm("Are you sure you want to clear your progress and start over?")) {
          setCategories(INITIAL_CHECKLIST);
          localStorage.removeItem('contentFlowState');
      }
  };

  const handleExport = () => {
    let exportText = "CONTENT STRATEGY PLAN\nGenerated by ContentFlow AI\n========================\n\n";
    
    categories.forEach(cat => {
        exportText += `[ ${cat.title} ]\n`;
        cat.items.forEach(item => {
            const status = item.isCompleted ? "[X]" : "[ ]";
            exportText += `${status} ${item.text}\n`;
            if (item.savedContent) {
                exportText += `   > NOTE: ${item.savedContent.replace(/\n/g, '\n   ')} \n`;
            }
        });
        exportText += "\n";
    });

    const blob = new Blob([exportText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'content-strategy-plan.txt';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className={isDarkMode ? 'dark' : ''}>
      <div className="min-h-screen bg-[#F8FAFC] dark:bg-slate-950 text-slate-800 dark:text-slate-100 flex flex-col md:flex-row font-sans selection:bg-indigo-100 dark:selection:bg-indigo-900 selection:text-indigo-900 dark:selection:text-indigo-100 transition-colors duration-300">
        
        {/* Sidebar / Left Panel */}
        <aside className="w-full md:w-80 lg:w-96 bg-white dark:bg-slate-900 border-r border-slate-200/60 dark:border-slate-800 md:h-screen md:sticky md:top-0 flex flex-col z-20 shadow-xl shadow-slate-200/40 dark:shadow-black/20 md:shadow-none transition-colors duration-300">
          <div className="p-8 border-b border-slate-100 dark:border-slate-800 flex justify-between items-start">
            <div>
              <div className="flex items-center gap-2.5 mb-2 text-indigo-600 dark:text-indigo-400">
                <div className="w-8 h-8 rounded-lg bg-indigo-600 text-white flex items-center justify-center shadow-lg shadow-indigo-500/30">
                    <LayoutDashboard size={18} strokeWidth={2.5} />
                </div>
                <h1 className="font-heading font-bold text-xl tracking-tight text-slate-900 dark:text-white">ContentFlow</h1>
              </div>
              <p className="text-xs text-slate-400 font-medium tracking-wide pl-1">AI-POWERED WORKFLOW</p>
            </div>
            
            <button 
              onClick={() => setIsDarkMode(!isDarkMode)}
              className="p-2 rounded-full bg-slate-100 dark:bg-slate-800 text-slate-500 dark:text-slate-400 hover:bg-slate-200 dark:hover:bg-slate-700 transition-colors"
              title="Toggle AI Theme"
            >
              {isDarkMode ? <Sun size={16} /> : <Moon size={16} />}
            </button>
          </div>

          <div className="p-6 flex-grow overflow-y-auto space-y-8">
            
            {/* Progress Section */}
            <div>
              <div className="flex justify-between text-sm font-bold text-slate-700 dark:text-slate-300 mb-3 tracking-tight">
                <span>Completion</span>
                <span className="text-indigo-600 dark:text-indigo-400">{progress}%</span>
              </div>
              <div className="w-full bg-slate-100 dark:bg-slate-800 rounded-full h-3 overflow-hidden p-[2px]">
                <div 
                  className="bg-gradient-to-r from-indigo-500 to-violet-500 h-full rounded-full transition-all duration-700 ease-out shadow-[0_0_10px_rgba(99,102,241,0.5)]" 
                  style={{ width: `${progress}%` }}
                ></div>
              </div>
            </div>

            <ContentMixChart data={INITIAL_CHART_DATA} isDarkMode={isDarkMode} />

            {/* Service CTA Section - Designed to Convert */}
            <div className="relative overflow-hidden rounded-2xl group cursor-pointer transition-transform duration-300 hover:scale-[1.02] border border-transparent dark:border-indigo-900/50">
              <div className="absolute inset-0 bg-slate-900 dark:bg-black z-0"></div>
              <div className="absolute top-0 right-0 w-32 h-32 bg-indigo-500 rounded-full blur-[50px] opacity-30 -mr-10 -mt-10 pointer-events-none"></div>
              <div className="absolute bottom-0 left-0 w-24 h-24 bg-violet-500 rounded-full blur-[40px] opacity-20 -ml-10 -mb-10 pointer-events-none"></div>
              
              <div className="relative z-10 p-6">
                  <div className="flex items-center gap-2 mb-3">
                      <div className="p-1.5 bg-yellow-500/20 rounded-lg">
                          <Zap size={16} className="text-yellow-400 fill-yellow-400" />
                      </div>
                      <h3 className="font-heading font-bold text-lg text-white tracking-tight">Scale Faster?</h3>
                  </div>
                  
                  <p className="text-slate-300 text-sm mb-5 leading-relaxed border-l-2 border-indigo-500/50 pl-3">
                    I build automated content engines that save businesses 20+ hours/week.
                  </p>
                  
                  <a 
                    href="#" 
                    onClick={(e) => e.preventDefault()}
                    className="flex items-center justify-between bg-white text-slate-900 text-sm font-bold py-3 px-4 rounded-xl transition-all hover:bg-indigo-50 group-hover:shadow-[0_0_20px_rgba(255,255,255,0.2)]"
                  >
                    Book Strategy Call <ArrowRight size={16} className="text-indigo-600 transition-transform group-hover:translate-x-1" />
                  </a>
                  <div className="mt-3 flex items-center justify-center gap-1.5 opacity-60">
                      <span className="w-1.5 h-1.5 rounded-full bg-green-400 animate-pulse"></span>
                      <span className="text-[10px] text-slate-300 uppercase tracking-widest font-semibold">2 Spots Left</span>
                  </div>
              </div>
            </div>

            {/* Action Buttons */}
            <div className="flex flex-col gap-3">
                <button 
                  onClick={handleExport}
                  className="flex items-center justify-center gap-2 text-sm font-semibold text-slate-600 dark:text-slate-300 hover:text-indigo-600 dark:hover:text-indigo-400 py-2.5 px-4 rounded-xl hover:bg-indigo-50/80 dark:hover:bg-indigo-900/30 transition-all border border-slate-200/80 dark:border-slate-800 bg-white dark:bg-slate-900 shadow-sm hover:shadow-md hover:border-indigo-100 dark:hover:border-indigo-800"
                >
                    <Download size={16} /> Download Strategy Plan
                </button>
                <button 
                  onClick={handleReset}
                  className="flex items-center justify-center gap-2 text-xs font-medium text-slate-400 hover:text-rose-500 py-2 transition-colors"
                >
                    <RefreshCw size={12} /> Reset Progress
                </button>
            </div>
          </div>
          
          <div className="p-6 border-t border-slate-100 dark:border-slate-800 text-center text-xs font-medium text-slate-300 dark:text-slate-600 tracking-wide uppercase">
            &copy; {new Date().getFullYear()} ContentFlow Systems
          </div>
        </aside>

        {/* Main Content Area */}
        <main className="flex-1 relative overflow-y-auto overflow-x-hidden">
          {/* Background Decorations */}
          <div className="absolute top-0 left-0 w-full h-96 bg-gradient-to-b from-indigo-50/50 dark:from-indigo-900/10 to-transparent pointer-events-none z-0"></div>
          <div className="absolute top-0 right-0 w-[500px] h-[500px] bg-indigo-100/40 dark:bg-indigo-600/5 rounded-full blur-[100px] -mr-40 -mt-40 pointer-events-none z-0"></div>

          <div className="relative z-10 p-6 md:p-10 lg:p-16 max-w-5xl mx-auto w-full">
              <header className="mb-12">
              <div className="flex flex-col md:flex-row md:justify-between md:items-start gap-4">
                  <div>
                      <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-indigo-50 dark:bg-indigo-900/30 border border-indigo-100 dark:border-indigo-800 text-indigo-600 dark:text-indigo-400 text-xs font-bold uppercase tracking-wider mb-4">
                          <Sparkles size={12} fill="currentColor" />
                          AI-Enhanced Workflow
                      </div>
                      <h2 className="font-heading text-4xl md:text-5xl font-extrabold text-slate-900 dark:text-white mb-4 tracking-tight leading-tight">
                          Content Creation <br/>
                          <span className="text-transparent bg-clip-text bg-gradient-to-r from-indigo-600 to-violet-600 dark:from-indigo-400 dark:to-violet-400">Master Checklist</span>
                      </h2>
                      <p className="text-lg text-slate-600 dark:text-slate-400 max-w-2xl leading-relaxed">
                          An actionable, expert-level roadmap to create high-converting content. Use the integrated AI tools to speed up every step.
                      </p>
                  </div>
              </div>
                  <div className="mt-8 flex flex-wrap gap-3">
                      <span className="inline-flex items-center gap-1.5 text-xs font-semibold text-slate-600 dark:text-slate-300 bg-white dark:bg-slate-800 px-4 py-2 rounded-full border border-slate-200 dark:border-slate-700 shadow-sm">
                          <Sparkles size={14} className="text-amber-500" />
                          Pro Tip: Expand items for expert insights
                      </span>
                      <span className="inline-flex items-center gap-1.5 text-xs font-semibold text-slate-600 dark:text-slate-300 bg-white dark:bg-slate-800 px-4 py-2 rounded-full border border-slate-200 dark:border-slate-700 shadow-sm">
                          <CheckCircle2 size={14} className="text-green-500" />
                          Auto-save enabled
                      </span>
                  </div>
              </header>

              <div className="space-y-12">
              {categories.map((category) => (
                  <div key={category.id} className="animate-fade-in-up">
                  <div className="flex items-center gap-4 mb-6 sticky top-0 bg-[#F8FAFC]/95 dark:bg-slate-950/95 backdrop-blur-sm py-4 z-10 md:static md:bg-transparent md:backdrop-blur-none transition-colors duration-300">
                      <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-indigo-500 to-violet-600 text-white flex items-center justify-center font-bold text-lg shadow-lg shadow-indigo-500/20">
                      {categories.indexOf(category) + 1}
                      </div>
                      <h3 className="font-heading text-2xl font-bold text-slate-800 dark:text-slate-100 tracking-tight">{category.title}</h3>
                  </div>
                  
                  <div className="space-y-4 pl-0 md:pl-14">
                      {category.items.map((item) => (
                      <ChecklistItem 
                          key={item.id} 
                          item={item} 
                          onToggle={handleToggleItem}
                          onAITrigger={handleAITrigger}
                      />
                      ))}
                  </div>
                  </div>
              ))}
              </div>

              {/* Completion State */}
              {progress === 100 && (
              <div className="mt-20 mb-10 bg-gradient-to-br from-green-50 to-emerald-50 dark:from-green-900/20 dark:to-emerald-900/20 border border-green-200 dark:border-green-800 rounded-3xl p-10 text-center animate-bounce-in shadow-xl shadow-green-500/10 relative overflow-hidden">
                  <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-green-300 to-emerald-400"></div>
                  <div className="w-20 h-20 bg-green-100 dark:bg-green-900/50 text-green-600 dark:text-green-400 rounded-full flex items-center justify-center mx-auto mb-6 shadow-inner">
                  <Rocket size={40} />
                  </div>
                  <h3 className="font-heading text-3xl font-bold text-green-900 dark:text-green-100 mb-3 tracking-tight">Ready to Publish!</h3>
                  <p className="text-green-800/80 dark:text-green-200/80 mb-8 max-w-lg mx-auto text-lg">
                  You've completed the entire workflow. Your content is optimized, polished, and ready to drive results.
                  </p>
                  <div className="flex flex-col sm:flex-row justify-center gap-4">
                      <button 
                      onClick={() => {
                          handleReset();
                          window.scrollTo({ top: 0, behavior: 'smooth' });
                      }}
                      className="bg-white dark:bg-transparent border-2 border-green-200 dark:border-green-700 text-green-700 dark:text-green-300 hover:border-green-300 hover:bg-green-50 dark:hover:bg-green-900/30 font-bold py-3 px-8 rounded-xl transition-all"
                      >
                      Start New Piece
                      </button>
                      <button 
                          onClick={handleExport}
                          className="bg-green-600 hover:bg-green-700 text-white font-bold py-3 px-8 rounded-xl transition-all shadow-lg shadow-green-600/30 flex items-center justify-center gap-2 hover:-translate-y-1"
                      >
                          <Download size={20} /> Download Plan
                      </button>
                  </div>
              </div>
              )}
          </div>
        </main>

        {/* AI Assistant Modal */}
        <AIAssistant 
          isOpen={isAIModalOpen}
          onClose={() => setIsAIModalOpen(false)}
          action={activeAIAction}
          contextTitle={activeAIContext}
          onSave={handleSaveAIContent}
        />
      </div>
    </div>
  );
};

export default App;