export interface ChecklistItem {
  id: string;
  text: string;
  description: string;
  isCompleted: boolean;
  aiAction?: AIActionType; // If this item has a specific AI tool attached
  expertTip?: string; // Expert advice to demonstrate authority
  savedContent?: string; // Content generated by AI and saved by user
}

export interface ChecklistCategory {
  id: string;
  title: string;
  items: ChecklistItem[];
}

export enum AIActionType {
  GENERATE_IDEAS = 'GENERATE_IDEAS',
  GENERATE_HOOKS = 'GENERATE_HOOKS',
  POLISH_CONTENT = 'POLISH_CONTENT',
  SEO_KEYWORDS = 'SEO_KEYWORDS',
  REPURPOSE_CONTENT = 'REPURPOSE_CONTENT',
  GENERATE_IMAGE = 'GENERATE_IMAGE'
}

export interface ChartData {
  name: string;
  value: number;
}
